### PR TITLE
[feature] msvc-static

### PR DESCRIPTION
**Pull request by gmh5225**
Github action: https://github.com/gmh5225/cmkr-msvc-static-testing/actions/runs/3167186905
Closes https://github.com/build-cpp/cmkr/issues/63

### CODE REVIEW

**Comment by mrexodia** [comment]
Thanks! Unfortunately I don't think this is the right way to implement things. I'll need to take a look again, but basically you need to also enable a policy because otherwise the property doesn't do anything. Right now you can achieve the same with:

```
[target.foo.properties]
MSVC_RUNTIME_LIBRARY = "MultiThreaded$<$<CONFIG:Debug>:Debug>"
```

**Comment by gmh5225** [comment]
Thank you for your reply, I am thinking about how to add a policy.

**Comment by gmh5225** [comment]
Artifacts: https://github.com/gmh5225/cmkr-msvc-static-testing/actions/runs/3201113555
image

**Comment by mrexodia** [comment]
Thanks, I think this is going in the right direction. For me the following would be a bit cleaner though:

```toml
[project]
name = "blah"
msvc-runtime = "static"

[target.dynamic-foo]
type = "executable"
msvc-runtime = "dynamic" # override the property

[target.static-foo]
type = "executable"
# has static runtime
```

The logic for the policy should also be a little different. It should error if you are trying to use `msvc-runtime` and the policy doesn't exist yet, but not emit the policy code if the `msvc-runtime` or `MSVC_RUNTIME_LIBRARY` are unset. If you don't have time to continue with this I can take over, just let me know.

**Comment by gmh5225** [comment]
This looks very good :)
I don't think I have that much time at the moment, but I really like this feature. thank you very much if you could take over

**Comment by mrexodia** [comment]
Finally for the tests to pass and documentation to generate properly, thanks for the PR!

**Comment by gmh5225** [comment]
Thanks. This is fantastic and I can't wait to test it out!

**Pull request merged**
